[2025-03-22T06:34:18.110+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_customer_dim scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T06:34:18.152+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_customer_dim scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T06:34:18.153+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-22T06:34:37.269+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): ingest_customer_dim> on 2025-03-21 00:00:00+00:00
[2025-03-22T06:34:37.285+0000] {standard_task_runner.py:57} INFO - Started process 200 to run task
[2025-03-22T06:34:37.575+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_batch_ingestion', 'ingest_customer_dim', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/loader_dag.py', '--cfg-path', '/tmp/tmpoxdbdsbd']
[2025-03-22T06:34:37.983+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask ingest_customer_dim
[2025-03-22T06:35:03.670+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_batch_ingestion.ingest_customer_dim scheduled__2025-03-21T00:00:00+00:00 [running]> on host c601b8b43588
[2025-03-22T06:35:05.106+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kebishaa' AIRFLOW_CTX_DAG_ID='dimension_batch_ingestion' AIRFLOW_CTX_TASK_ID='ingest_customer_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-22T06:35:06.755+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-22T06:35:06.756+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -X POST -F file=@/opt/***/customer_dim_large_data.csv -H "Content-Type: multipart/form-data" "http://pinot-controller:9000/ingestFromFile?tableNameWithType=customer_dim_OFFLINE&batchConfigMapStr=%7B%22inputFormat%22%3A%22csv%22%2C%22recordReader.prop.delimiter%22%3A%22%2C%22%7D"']
[2025-03-22T06:35:06.939+0000] {subprocess.py:86} INFO - Output:
[2025-03-22T06:35:15.121+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-03-22T06:35:15.123+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-03-22T06:35:16.239+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[2025-03-22T06:35:16.242+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to pinot-controller port 9000: Connection refused
[2025-03-22T06:35:16.462+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2025-03-22T06:35:16.497+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2025-03-22T06:35:16.798+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dimension_batch_ingestion, task_id=ingest_customer_dim, execution_date=20250321T000000, start_date=20250322T063418, end_date=20250322T063516
[2025-03-22T06:35:17.248+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 39 for task ingest_customer_dim (Bash command failed. The command returned a non-zero exit code 7.; 200)
[2025-03-22T06:35:17.304+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-22T06:35:17.774+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
