[2025-03-22T06:34:17.448+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T06:34:17.820+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T06:34:17.821+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-22T06:34:37.272+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): ingest_account_dim> on 2025-03-21 00:00:00+00:00
[2025-03-22T06:34:37.288+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2025-03-22T06:34:37.948+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_batch_ingestion', 'ingest_account_dim', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/loader_dag.py', '--cfg-path', '/tmp/tmp10phbzz5']
[2025-03-22T06:34:38.357+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask ingest_account_dim
[2025-03-22T06:35:04.146+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2025-03-21T00:00:00+00:00 [running]> on host c601b8b43588
[2025-03-22T06:35:05.404+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kebishaa' AIRFLOW_CTX_DAG_ID='dimension_batch_ingestion' AIRFLOW_CTX_TASK_ID='ingest_account_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-22T06:35:06.686+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-22T06:35:06.689+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -X POST -F file=@/opt/***/account_dim_large_data.csv -H "Content-Type: multipart/form-data" "http://pinot-controller:9000/ingestFromFile?tableNameWithType=account_dim_OFFLINE&batchConfigMapStr=%7B%22inputFormat%22%3A%22csv%22%2C%22recordReader.prop.delimiter%22%3A%22%2C%22%7D"']
[2025-03-22T06:35:06.939+0000] {subprocess.py:86} INFO - Output:
[2025-03-22T06:35:15.126+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-03-22T06:35:15.128+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-03-22T06:35:16.232+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[2025-03-22T06:35:16.235+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to pinot-controller port 9000: Connection refused
[2025-03-22T06:35:16.462+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2025-03-22T06:35:16.492+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2025-03-22T06:35:16.864+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dimension_batch_ingestion, task_id=ingest_account_dim, execution_date=20250321T000000, start_date=20250322T063417, end_date=20250322T063516
[2025-03-22T06:35:17.557+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task ingest_account_dim (Bash command failed. The command returned a non-zero exit code 7.; 201)
[2025-03-22T06:35:17.602+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-22T06:35:17.964+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
