[2025-03-20T21:08:17.759+0000] {processor.py:157} INFO - Started process (PID=6255) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:08:17.761+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:08:17.765+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:08:17.764+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:08:17.844+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:08:17.772+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:08:17.848+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:08:18.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.359 seconds
[2025-03-20T21:09:15.301+0000] {processor.py:157} INFO - Started process (PID=6284) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:09:16.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:09:16.275+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:09:16.272+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:09:16.546+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:09:16.539+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:09:16.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:09:17.071+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 1.963 seconds
[2025-03-20T21:10:33.828+0000] {processor.py:157} INFO - Started process (PID=6322) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:10:33.831+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:10:33.834+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:10:33.833+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:10:33.848+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:10:33.845+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:10:33.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:10:34.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.522 seconds
[2025-03-20T21:12:08.442+0000] {processor.py:157} INFO - Started process (PID=6346) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:12:08.446+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:12:08.450+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:12:08.449+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:12:09.363+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:12:08.716+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:12:09.365+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:12:11.586+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 3.153 seconds
[2025-03-20T21:13:27.510+0000] {processor.py:157} INFO - Started process (PID=6370) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:13:27.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:13:27.516+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:13:27.515+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:13:27.686+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:13:27.522+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:13:27.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:13:31.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 3.699 seconds
[2025-03-20T21:15:12.630+0000] {processor.py:157} INFO - Started process (PID=6391) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:15:12.638+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:15:12.655+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:15:12.651+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:15:12.923+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:15:12.794+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:15:12.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:15:16.049+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 3.542 seconds
[2025-03-20T21:15:57.489+0000] {processor.py:157} INFO - Started process (PID=6416) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:15:57.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:15:57.788+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:15:57.675+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:15:58.269+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:15:58.226+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:15:58.276+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:15:58.898+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 1.821 seconds
[2025-03-20T21:16:58.392+0000] {processor.py:157} INFO - Started process (PID=6450) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:16:58.410+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:16:58.422+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:16:58.417+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:16:58.500+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:16:58.452+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:16:58.513+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:16:58.799+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.428 seconds
[2025-03-20T21:17:35.621+0000] {processor.py:157} INFO - Started process (PID=6487) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:17:35.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:17:35.633+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:17:35.631+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:17:35.666+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:17:35.653+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:17:35.668+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:17:35.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.306 seconds
[2025-03-20T21:18:06.441+0000] {processor.py:157} INFO - Started process (PID=6515) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:18:06.444+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:18:06.452+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:18:06.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:18:06.470+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:18:06.466+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:18:06.476+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:18:06.685+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.256 seconds
[2025-03-20T21:18:40.358+0000] {processor.py:157} INFO - Started process (PID=6555) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:18:40.387+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:18:40.731+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:18:40.641+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:18:42.373+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:18:42.329+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:18:42.375+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:18:42.779+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 3.323 seconds
[2025-03-20T21:19:13.027+0000] {processor.py:157} INFO - Started process (PID=6595) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:19:13.029+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:19:13.032+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:19:13.031+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:19:13.045+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:19:13.043+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:19:13.046+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:19:13.205+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.186 seconds
[2025-03-20T21:19:43.941+0000] {processor.py:157} INFO - Started process (PID=6635) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:19:43.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:19:43.953+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:19:43.953+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:19:43.970+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:19:43.966+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:19:43.971+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:19:44.045+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.119 seconds
[2025-03-20T21:20:14.171+0000] {processor.py:157} INFO - Started process (PID=6675) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:20:14.176+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:20:14.180+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:20:14.179+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:20:14.203+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:20:14.201+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:20:14.205+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:20:14.469+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.307 seconds
[2025-03-20T21:20:44.539+0000] {processor.py:157} INFO - Started process (PID=6715) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:20:44.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:20:44.546+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:20:44.545+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:20:44.556+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:20:44.554+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:20:44.558+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:20:44.643+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.115 seconds
[2025-03-20T21:21:15.416+0000] {processor.py:157} INFO - Started process (PID=6755) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:21:15.421+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:21:15.425+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:21:15.424+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:21:15.441+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:21:15.438+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:21:15.442+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:21:15.574+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.169 seconds
[2025-03-20T21:21:46.218+0000] {processor.py:157} INFO - Started process (PID=6795) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:21:46.220+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:21:46.223+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:21:46.223+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:21:46.240+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:21:46.236+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:21:46.241+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:21:46.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.077 seconds
[2025-03-20T21:22:16.344+0000] {processor.py:157} INFO - Started process (PID=6835) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:22:16.352+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:22:16.355+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:22:16.354+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:22:16.375+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:22:16.372+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:22:16.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:22:16.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.114 seconds
[2025-03-20T21:22:47.351+0000] {processor.py:157} INFO - Started process (PID=6875) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:22:47.354+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:22:47.358+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:22:47.357+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:22:47.366+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:22:47.365+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:22:47.367+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:22:47.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.075 seconds
[2025-03-20T21:23:17.642+0000] {processor.py:157} INFO - Started process (PID=6915) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:23:17.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:23:17.652+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:23:17.650+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:23:17.666+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:23:17.663+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:23:17.669+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:23:17.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.121 seconds
[2025-03-20T21:23:47.974+0000] {processor.py:157} INFO - Started process (PID=6955) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:23:47.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:23:47.979+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:23:47.978+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:23:47.991+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:23:47.989+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:23:47.993+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:23:48.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.087 seconds
[2025-03-20T21:24:18.109+0000] {processor.py:157} INFO - Started process (PID=6995) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:24:18.115+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:24:18.119+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:24:18.118+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:24:18.128+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:24:18.126+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:24:18.130+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:24:18.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.094 seconds
[2025-03-20T21:24:48.501+0000] {processor.py:157} INFO - Started process (PID=7035) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:24:48.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:24:48.507+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:24:48.506+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:24:48.522+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:24:48.520+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:24:48.524+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:24:48.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.114 seconds
[2025-03-20T21:25:18.869+0000] {processor.py:157} INFO - Started process (PID=7075) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:25:18.876+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:25:18.879+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:25:18.879+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:25:18.893+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:25:18.889+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:25:18.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:25:18.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.122 seconds
[2025-03-20T21:25:49.659+0000] {processor.py:157} INFO - Started process (PID=7107) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:25:49.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:25:49.669+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:25:49.668+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:25:49.687+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:25:49.684+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:25:49.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:25:49.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.151 seconds
[2025-03-20T21:26:20.253+0000] {processor.py:157} INFO - Started process (PID=7137) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:26:20.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:26:20.259+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:26:20.258+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:26:20.280+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:26:20.277+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:26:20.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:26:20.395+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.153 seconds
[2025-03-20T21:26:50.680+0000] {processor.py:157} INFO - Started process (PID=7175) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:26:50.682+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:26:50.686+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:26:50.685+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:26:50.701+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:26:50.697+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:26:50.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:26:50.841+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.174 seconds
[2025-03-20T21:27:21.268+0000] {processor.py:157} INFO - Started process (PID=7209) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:27:21.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:27:21.280+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:27:21.277+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:27:21.302+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:27:21.300+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:27:21.307+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:27:21.616+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.372 seconds
[2025-03-20T21:27:52.120+0000] {processor.py:157} INFO - Started process (PID=7245) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:27:52.123+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:27:52.127+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:27:52.126+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:27:52.147+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:27:52.144+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:27:52.148+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:27:52.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.120 seconds
[2025-03-20T21:28:22.315+0000] {processor.py:157} INFO - Started process (PID=7285) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:28:22.318+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:28:22.321+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:28:22.320+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:28:22.331+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:28:22.328+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:28:22.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:28:22.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.090 seconds
[2025-03-20T21:28:52.583+0000] {processor.py:157} INFO - Started process (PID=7325) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:28:52.586+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:28:52.590+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:28:52.588+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:28:52.604+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:28:52.602+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:28:52.609+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:28:52.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.125 seconds
[2025-03-20T21:29:23.236+0000] {processor.py:157} INFO - Started process (PID=7365) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:29:23.253+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:29:23.261+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:29:23.260+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:29:23.286+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:29:23.283+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:29:23.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:29:23.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.180 seconds
[2025-03-20T21:29:54.035+0000] {processor.py:157} INFO - Started process (PID=7405) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:29:54.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:29:54.048+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:29:54.048+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:29:54.072+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:29:54.068+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:29:54.073+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:29:54.163+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.145 seconds
[2025-03-20T21:30:24.688+0000] {processor.py:157} INFO - Started process (PID=7445) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:30:24.691+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:30:24.694+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:30:24.693+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:30:24.702+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:30:24.700+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:30:24.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:30:24.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.069 seconds
[2025-03-20T21:30:54.874+0000] {processor.py:157} INFO - Started process (PID=7485) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:30:54.876+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:30:54.879+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:30:54.878+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:30:54.888+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:30:54.887+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:30:54.890+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:30:54.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.069 seconds
[2025-03-20T21:31:25.505+0000] {processor.py:157} INFO - Started process (PID=7525) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:31:25.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:31:25.510+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:31:25.509+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:31:25.518+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:31:25.517+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:31:25.520+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:31:25.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.210 seconds
[2025-03-20T21:31:56.178+0000] {processor.py:157} INFO - Started process (PID=7565) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:31:56.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:31:56.183+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:31:56.182+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:31:56.192+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:31:56.189+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:31:56.193+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:31:56.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.077 seconds
[2025-03-20T21:32:26.375+0000] {processor.py:157} INFO - Started process (PID=7605) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:32:26.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:32:26.381+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:32:26.380+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:32:26.390+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:32:26.388+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:32:26.391+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:32:26.450+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.084 seconds
[2025-03-20T21:32:56.949+0000] {processor.py:157} INFO - Started process (PID=7645) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:32:56.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:32:56.954+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:32:56.953+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:32:56.978+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:32:56.973+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:32:56.981+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:32:57.039+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.097 seconds
[2025-03-20T21:33:27.259+0000] {processor.py:157} INFO - Started process (PID=7685) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:33:27.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:33:27.268+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:33:27.266+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:33:27.279+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:33:27.276+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:33:27.281+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:33:27.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.102 seconds
[2025-03-20T21:33:57.851+0000] {processor.py:157} INFO - Started process (PID=7725) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:33:57.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:33:57.857+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:33:57.857+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:33:57.867+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:33:57.865+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:33:57.869+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:33:57.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.093 seconds
[2025-03-20T21:34:28.148+0000] {processor.py:157} INFO - Started process (PID=7763) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:34:28.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:34:28.162+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:34:28.161+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:34:28.194+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:34:28.184+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:34:28.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:34:28.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.179 seconds
[2025-03-20T21:34:59.028+0000] {processor.py:157} INFO - Started process (PID=7799) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:34:59.038+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:34:59.054+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:34:59.048+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:34:59.110+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:34:59.099+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:34:59.118+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:34:59.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.384 seconds
[2025-03-20T21:35:29.942+0000] {processor.py:157} INFO - Started process (PID=7837) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:35:29.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:35:29.947+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:35:29.946+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:35:29.963+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:35:29.960+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:35:29.966+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:35:30.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.105 seconds
[2025-03-20T21:36:01.958+0000] {processor.py:157} INFO - Started process (PID=7873) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:36:01.964+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:36:01.967+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:36:01.966+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:36:02.015+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:36:02.004+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:36:02.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:36:02.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.163 seconds
[2025-03-20T21:36:32.370+0000] {processor.py:157} INFO - Started process (PID=7896) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:36:32.372+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:36:32.375+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:36:32.374+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:36:32.394+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:36:32.391+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:36:32.396+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:36:32.487+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.128 seconds
[2025-03-20T21:37:02.755+0000] {processor.py:157} INFO - Started process (PID=7934) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:37:02.758+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:37:02.769+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:37:02.768+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:37:02.789+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:37:02.786+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:37:02.792+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:37:02.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.179 seconds
[2025-03-20T21:37:33.099+0000] {processor.py:157} INFO - Started process (PID=7970) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:37:33.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:37:33.107+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:37:33.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:37:33.122+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:37:33.118+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:37:33.126+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:37:33.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.136 seconds
[2025-03-20T21:38:03.968+0000] {processor.py:157} INFO - Started process (PID=8010) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:38:03.971+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:38:03.974+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:38:03.973+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:38:03.986+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:38:03.983+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:38:03.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:38:04.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.189 seconds
[2025-03-20T21:38:34.885+0000] {processor.py:157} INFO - Started process (PID=8050) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:38:34.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:38:34.891+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:38:34.890+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:38:34.900+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:38:34.897+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:38:34.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:38:34.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.070 seconds
[2025-03-20T21:39:05.550+0000] {processor.py:157} INFO - Started process (PID=8090) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:39:05.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:39:05.574+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:39:05.557+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:39:05.607+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:39:05.596+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:39:05.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:39:05.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.219 seconds
[2025-03-20T21:39:36.297+0000] {processor.py:157} INFO - Started process (PID=8130) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:39:36.299+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:39:36.304+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:39:36.303+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:39:36.320+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:39:36.316+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:39:36.327+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:39:36.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.124 seconds
[2025-03-20T21:40:06.588+0000] {processor.py:157} INFO - Started process (PID=8170) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:40:06.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:40:06.602+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:40:06.601+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:40:06.640+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:40:06.633+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:40:06.644+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:40:06.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.306 seconds
[2025-03-20T21:40:37.706+0000] {processor.py:157} INFO - Started process (PID=8208) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:40:37.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:40:37.716+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:40:37.715+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:40:37.741+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:40:37.735+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:40:37.743+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:40:37.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.191 seconds
[2025-03-20T21:41:08.501+0000] {processor.py:157} INFO - Started process (PID=8244) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:41:08.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:41:08.510+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:41:08.509+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:41:08.623+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:41:08.598+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:41:08.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:41:08.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.247 seconds
[2025-03-20T21:41:39.405+0000] {processor.py:157} INFO - Started process (PID=8272) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:41:39.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:41:39.419+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:41:39.418+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:41:39.483+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:41:39.460+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:41:39.484+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:41:39.746+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.362 seconds
[2025-03-20T21:42:10.116+0000] {processor.py:157} INFO - Started process (PID=8312) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:42:10.124+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:42:10.133+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:42:10.132+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:42:10.205+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:42:10.156+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:42:10.212+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:42:10.362+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.259 seconds
[2025-03-20T21:42:41.040+0000] {processor.py:157} INFO - Started process (PID=8352) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:42:41.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:42:41.045+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:42:41.044+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:42:41.058+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:42:41.054+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:42:41.059+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:42:41.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.175 seconds
[2025-03-20T21:43:12.690+0000] {processor.py:157} INFO - Started process (PID=8390) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:43:12.697+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:43:12.704+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:43:12.702+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:43:12.718+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:43:12.716+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:43:12.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:43:12.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.103 seconds
[2025-03-20T21:43:44.908+0000] {processor.py:157} INFO - Started process (PID=8426) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:43:44.910+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:43:44.913+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:43:44.912+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:43:44.934+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:43:44.931+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:43:44.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:43:45.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.254 seconds
[2025-03-20T21:44:15.350+0000] {processor.py:157} INFO - Started process (PID=8454) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:44:15.360+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:44:15.368+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:44:15.367+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:44:15.399+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:44:15.395+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:44:15.416+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:44:15.570+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.273 seconds
[2025-03-20T21:44:47.299+0000] {processor.py:157} INFO - Started process (PID=8487) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:44:47.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:44:47.316+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:44:47.315+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:44:47.350+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:44:47.340+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:44:47.352+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:44:47.524+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.242 seconds
[2025-03-20T21:45:20.391+0000] {processor.py:157} INFO - Started process (PID=8527) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:45:20.421+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:45:20.446+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:45:20.445+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:45:20.520+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:45:20.513+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:45:20.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:45:20.716+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.363 seconds
[2025-03-20T21:45:54.292+0000] {processor.py:157} INFO - Started process (PID=8567) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:45:54.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:45:54.307+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:45:54.306+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:45:54.350+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:45:54.345+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:45:54.364+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:45:54.539+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.259 seconds
[2025-03-20T21:46:24.962+0000] {processor.py:157} INFO - Started process (PID=8597) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:46:24.968+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:46:24.972+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:46:24.971+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:46:24.999+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:46:24.996+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:46:25.001+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:46:25.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.179 seconds
[2025-03-20T21:46:55.601+0000] {processor.py:157} INFO - Started process (PID=8637) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:46:55.610+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:46:55.619+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:46:55.618+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:46:55.660+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:46:55.646+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:46:55.663+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:46:55.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.244 seconds
[2025-03-20T21:47:25.973+0000] {processor.py:157} INFO - Started process (PID=8677) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:47:25.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:47:25.984+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:47:25.982+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:47:26.021+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:47:26.014+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:47:26.028+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:47:26.261+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.302 seconds
[2025-03-20T21:47:56.944+0000] {processor.py:157} INFO - Started process (PID=8717) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:47:56.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:47:56.958+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:47:56.957+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:47:56.986+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:47:56.979+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:47:56.992+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:47:57.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.167 seconds
[2025-03-20T21:48:30.403+0000] {processor.py:157} INFO - Started process (PID=8757) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:48:30.420+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:48:30.730+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:48:30.653+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:48:33.413+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:48:33.316+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:48:33.416+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:48:34.185+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 5.259 seconds
[2025-03-20T21:49:04.817+0000] {processor.py:157} INFO - Started process (PID=8797) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:49:04.829+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:49:04.833+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:49:04.832+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:49:04.871+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:49:04.868+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:49:04.876+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:49:05.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.223 seconds
[2025-03-20T21:49:35.952+0000] {processor.py:157} INFO - Started process (PID=8837) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:49:35.999+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:49:36.011+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:49:36.009+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:49:36.468+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:49:36.465+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:49:36.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:49:37.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 1.804 seconds
[2025-03-20T21:50:08.474+0000] {processor.py:157} INFO - Started process (PID=8877) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:50:08.478+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:50:08.481+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:50:08.480+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:50:08.489+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:50:08.487+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:50:08.490+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:50:08.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.090 seconds
[2025-03-20T21:50:39.076+0000] {processor.py:157} INFO - Started process (PID=8917) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:50:39.179+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:50:39.211+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:50:39.209+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:50:39.823+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:50:39.819+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:50:39.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:50:40.161+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 1.103 seconds
[2025-03-20T21:51:10.439+0000] {processor.py:157} INFO - Started process (PID=8957) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:51:10.441+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:51:10.444+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:51:10.443+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:51:10.455+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:51:10.452+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:51:10.456+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:51:10.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.174 seconds
[2025-03-20T21:52:12.487+0000] {processor.py:157} INFO - Started process (PID=8977) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:52:14.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:52:15.173+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:52:14.474+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:52:28.789+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:52:25.685+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:52:28.972+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:52:56.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 48.010 seconds
[2025-03-20T21:53:52.935+0000] {processor.py:157} INFO - Started process (PID=8994) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:53:52.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:53:52.960+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:53:52.959+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:53:53.137+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:53:53.135+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:53:53.152+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:53:56.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 3.580 seconds
[2025-03-20T21:55:26.776+0000] {processor.py:157} INFO - Started process (PID=9010) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:55:26.794+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:55:26.816+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:55:26.807+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:55:26.874+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:55:26.861+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:55:26.883+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:55:27.361+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.593 seconds
[2025-03-20T21:56:02.724+0000] {processor.py:157} INFO - Started process (PID=9045) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:56:02.776+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:56:02.783+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:56:02.780+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:56:02.906+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:56:02.896+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:56:02.912+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:56:03.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.653 seconds
[2025-03-20T21:56:52.429+0000] {processor.py:157} INFO - Started process (PID=9081) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:56:52.432+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:56:52.435+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:56:52.434+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:56:52.444+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:56:52.442+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:56:52.446+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:56:52.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.296 seconds
[2025-03-20T21:59:03.424+0000] {processor.py:157} INFO - Started process (PID=9113) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:59:03.428+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:59:03.432+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:59:03.432+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:59:03.443+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:59:03.440+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:59:03.445+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:59:04.560+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 1.144 seconds
[2025-03-20T21:59:35.163+0000] {processor.py:157} INFO - Started process (PID=9147) to work on /opt/airflow/dags/loader_dag.py
[2025-03-20T21:59:35.166+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/loader_dag.py for tasks to queue
[2025-03-20T21:59:35.169+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:59:35.168+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:59:35.176+0000] {logging_mixin.py:151} INFO - [2025-03-20T21:59:35.175+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/loader_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader_dag.py", line 16
    schedule_interval='@daily'
    ^
SyntaxError: invalid syntax
[2025-03-20T21:59:35.177+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/loader_dag.py
[2025-03-20T21:59:35.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/loader_dag.py took 0.118 seconds
